### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by Ritchielambda** [jamiebk/OpenMesh_UE4#1]
I include MeshIO.hh, I get the following error:  MyActor.cpp.obj : error LNK2019:and many link2001 error
I recognize that I am skirting around an incredible c++ issues, so I appreciate any patience.

**Comment by jamiebk** [comment]
Hi, I don't think your issue would have anything to do with the changes in this fork. By the sound of it you haven't linked the lib files for OpenMesh to your unreal build. See:
[https://wiki.unrealengine.com/Linking_Static_Libraries_Using_The_Build_System]().
